logging:
  level:
    org:
      springframework:
        amqp: debug

spring:
  rabbitmq:
    addresses: localhost:5672

  cloud:
    function: 
      definition: messagesConsumer
    stream:
      bindings:
        messagesConsumer-in-0:
          destination: messages