server:
  port: 8020

logging:
  level:
    org:
      springframework:
        amqp: debug

spring:
  rabbitmq:
    addresses: localhost:5672

  cloud:
    function:
      definition: messagesProcessor
    stream:
      bindings:
        messagesProcessor-in-0:
          destination: alerts
        messagesProcessor-out-0:
          destination: integrations
